title: Marketing for Change by Cameron Ottens
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.7670251
  brandStrength: 0.5179211
  lightness: 0.7831541
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  rhythmicContrast: 0.7921147
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: change
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.03862745477817953
layout_spectrum: 0.1040396811440587
